apiVersion: v1
kind: Secret
metadata:
    name: collector-secrets
    namespace: collectors
type: Opaque
stringData:
    MYSQL_PASSWORD: ENC[AES256_GCM,data:nCiyHumF684UzcN69TSy77jkZQ==,iv:FXAmAY5/+P/sA4odDBCKPL8WzrJi2Mi5ezDlbpRd9Wc=,tag:Qrv7/468pKm8K+UFWk/t9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpLzExSHdLaUtqOGxab3hq
            anZzeVY0a0NCOE03cFI3c0RzbzArQmpsWVFZClA0VHZEWWpZVmNHWU9uNlpVbVVT
            d0MyMlRrQUVkVXp2WnZrRzM2eHFBUmsKLS0tIDlCNHNrTVNsVkNlTHVwWTBGdlFi
            cUNCK3MxeWl1WnNoQ25tV21nb0NibDQKEoXEAG508xpBoSFXDf0YsqPh9m0U6F50
            c0u6HJ6WDG49x73/AK1a86ZDVf8sIKz48tce9TpokXRGv/lFcKUa4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mvxx3fjdx3k40ycajr5wakumf2vklxqtw68xw3u2eukqwmyf3zqff66ak
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T06:36:26Z"
    mac: ENC[AES256_GCM,data:MuNG6EXaS+Smq+w8AT8IY6ODnVevDpK1al7bkpziBeqMsqzyg8LDeQVmJXu3G9Fj6mBQTHh6VpR80iekmumC92J9OL445pZ6YmgTiPl5/f4rNuR8PcutIdKrv5AbUljUIAvvbSR4hg9mK0Ki9c09EHYfd60ZUvtwXZpxd4aCTZk=,iv:izNNvWmSPtytz/wkjj3E0LF5G0TQFJEB+GQLn0xJ8i4=,tag:Bp0Ip2XFmaZPjWRK4mh95Q==,type:str]
    version: 3.13.3
