apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collectors
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    repoURL: https://github.com/charleschen68/big-data-platform-envs.git
    targetRevision: feat/gitops-data-collectors
    path: environments/current/overlays/collectors
  destination:
    server: https://kubernetes.default.svc
    namespace: collectors
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
