apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: platform
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/argocd.argoproj.io~1tracking-id
      jqPathExpressions:
        - .metadata.annotations."argocd.argoproj.io/tracking-id"
  source:
    repoURL: https://github.com/charleschen68/big-data-platform-envs.git
    targetRevision: feat/gitops-data-collectors
    path: environments/current/overlays/data
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
