apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: platform
  source:
    repoURL: https://github.com/charleschen68/big-data-platform-envs.git
    targetRevision: feat/gitops-data-collectors
    path: environments/current/overlays/data
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
