apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: platform
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      parameters:
        - name: mode
          value: standalone
        - name: existingSecret
          value: minio-secrets
        - name: persistence.enabled
          value: "true"
        - name: persistence.storageClass
          value: local-path
        - name: persistence.size
          value: 20Gi
        - name: resources.requests.cpu
          value: 250m
        - name: resources.requests.memory
          value: 512Mi
        - name: resources.limits.cpu
          value: "1"
        - name: resources.limits.memory
          value: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
