apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-self
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  project: platform
  source:
    repoURL: https://github.com/charleschen68/big-data-platform-envs.git
    targetRevision: HEAD
    path: environments/current
    plugin:
      name: ksops
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
