apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  project: platform
  source:
    repoURL: https://github.com/charleschen68/big-data-platform-envs.git
    targetRevision: HEAD
    path: environments/current/overlays/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
