apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 88.1.5
      helm:
        releaseName: monitoring
        valueFiles:
          - $values/environments/current/overlays/observability/monitoring-values.yaml
    - repoURL: https://github.com/charleschen68/big-data-platform-envs.git
      targetRevision: feat/gitops-data-collectors
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
