apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: ExternalName
  externalName: kafka-kafka-bootstrap.data.svc.cluster.local
  ports:
    - name: kafka
      port: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ExternalName
  externalName: mysql.data.svc.cluster.local
  ports:
    - name: mysql
      port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: milvus
spec:
  type: ExternalName
  externalName: milvus.data.svc.cluster.local
  ports:
    - name: milvus
      port: 19530
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  type: ExternalName
  externalName: clickhouse.data.svc.cluster.local
  ports:
    - name: clickhouse
      port: 9000
