apiVersion: v1
kind: Secret
metadata:
    name: flink-state-secrets
    namespace: flink
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:zTmr73R5l+WhCVlNduSTGcZu8g==,iv:fGUSTuzvpdb1Lqyo1e0E6JLO0c8btImnLMBY/ydKjUQ=,tag:ksiu5jr/zkr/4r5xaxRjIA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hfEiUtbFPzn6Siql9P4dnoniBHyB687EyhKACWSd2VLAQ7ug5xUVgk6kpJSxzlZI,iv:2pAXFI348pDQnjtlz0bizrg3nlIJAKLS8rvF8OTxwjY=,tag:uygy4+6/wczLqnGf71Ybzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRGZPTDA5bGZ6S0dVOEdr
            YUc2WWFHYjFDUlFmUEZpTHVySnJya1RMbkM0ClJGd1ZWUzRvK2NsSVI1QTNVMU5x
            THFubENJL1lxRkRKRGczRjdCMnlnVDAKLS0tIG9GbnR1bXRqWlNEU1VtdXpKZU43
            WGZwVk1kb2laL21hUWhHVnJITjB6elkKLIsNoUyrBPH8qIl7hccyWi6jQdHUtizW
            XRdpFOrbjDmgjKYvi3wZR2BZgi48Tg56TyrWzCtOChBx9OvmuX3N0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mvxx3fjdx3k40ycajr5wakumf2vklxqtw68xw3u2eukqwmyf3zqff66ak
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T05:01:59Z"
    mac: ENC[AES256_GCM,data:J8qkAYecXUzRek/h4rIyc9HLV1cvH8iSUavPsJ8tPA73A2rN6YGRMUWAxJatz5ZVmclZ9jxYad/PtB8L0uhGsNzi0PBvt16o3BPRyktXJNd3LMh0+wziq5IEkdx8y417VerFfIAjdLSA4vocLOiwtgKtZWeHcapxeuZlZy/H7UM=,iv:emlojvxqykRQXXCFdt/BZFsy3xzoDEI5ckUKhvQ6/wM=,tag:if47rH/3gRtUJ6ufkFfPhw==,type:str]
    version: 3.13.3
