apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications/gitops.yaml
  - projects/platform.yaml
  - applications/ingress.yaml
  - applications/data-prerequisites.yaml
  - applications/data.yaml
  - applications/collectors.yaml
  - applications/observability.yaml
  - secrets
