apiVersion: v1
kind: Secret
metadata:
    name: kafka-secrets
    namespace: data
type: Opaque
stringData:
    KAFKA_USERNAME: ENC[AES256_GCM,data:597IHUkaaWXnhA==,iv:9SFDvA15RIkFu2ME22lcxwx/OveM3ZGSn1m3h3Rb0x0=,tag:wP+7AOfAxPp75x0IJER78Q==,type:str]
    KAFKA_PASSWORD: ENC[AES256_GCM,data:tHFzh3c4bwwixJTFNEA=,iv:4jXHCBuNf+K/HBHb7a0mgd/4B4GHOTzPVEdmXdhPP4U=,tag:OcgZm2rTFUYsAHzuwupHjg==,type:str]
    KAFKA_BOOTSTRAP_SERVERS: ENC[AES256_GCM,data:YlSwr+zUZeTfHIuwZgzTurcUBIUkHooeaajj/d5W8ZlJ7f5W79zIViGpbchFEw0ehA==,iv:xTml5KmAABIb+OHNYWlX+xKpHM7yM20XFUiRY6MsdPE=,tag:vseRyISCEnFXTsi47JW8nQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeFJIMFc3UG1kdXZwSjh4
            ZFhNWDYzNTd6Wm9qQWk4ZFRvdlU2U0wyN3cwCmQwY1ZaM1NxVHNpczR6Q05BaEhM
            aDJuOUd1WmhNU0t6Ym1YS21sa1FPdDQKLS0tIE16RUxPR3F4NEdLclNtZ1pDZTNq
            SmNlMjhFN0xUVDNiRXY2d1pDYWZ6WHMKub9yeQv9kzEDVI5f7y46nNgM3mtcLveY
            txyRUqJDmUxWL/OpPHz+He4+OSXx4+Er4/U14Hjlin0XpB5z8aKTTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mvxx3fjdx3k40ycajr5wakumf2vklxqtw68xw3u2eukqwmyf3zqff66ak
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T08:27:19Z"
    mac: ENC[AES256_GCM,data:kEIPNTqND7VcQ6yB0y9eRI8Pmo1E1uBZMXQ/sVkxjdEvFZJEnXPuYe3TQdM+NKVC1VvzQ+jAy9Bi8BcDzushKk6zgJQ/KfZS+fNzavH12YcPcEYmTMEcsqdEdjG2yz98wM5DksOpUgFp5ugdBg5o4Ir787PeKReIIYHBjE4pylk=,iv:mMZzke/OUY2jPnvEEpHms0Yu1wUweZaFvj9ArAOqNdo=,tag:rfKJ8gAQLUXuDW5nliMvXA==,type:str]
    version: 3.13.3
