apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: kafka-secrets
    files:
      - kafka-secrets.sops.yaml
  - name: mysql-secrets
    files:
      - mysql-secrets.sops.yaml
  - name: minio-secrets
    files:
      - minio-secrets.sops.yaml

generatorOptions:
  annotations:
    sops.unsealed: "true"
