apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: data
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:IyLNhbnCb1USrgU=,iv:kCBHBkLEe3PSKORi74TTZn3rEIXoYcCUAwYOAp7AfjY=,tag:Y32YpdAusTs/uvLJhzYS2A==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:7kMNYXI76Q7mRR/7An/raDml2sU2,iv:OA/KYuH7fFpr2+h2NfVAiQnAzrm2lw2JreidjCTZBR4=,tag:xQu8fGdGLgzZKuzRX1hBjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHczRBbDBDbEdoTUhEaUJB
            cGR1OEhzZE1sN0poYTY1ckJQZHV2M25YUkhzCnhNK3VOYUFKdWRuOC9uMDBHMEJN
            WVBWN1U4V3hOdEVyblBSZWtXOGhxYTAKLS0tIFRjTHVUUUtBMFdiT1JHWG1VMUxU
            VmFpbW1Ld3RMUGhnbTZlUXhnSDhBRzgKhE1OJIVvI32jGYyzQg1xbJjSQgPZ3EKP
            TmNJ8UEJVRqz1gWuFzdrzzhW5waewCvgElbf6mnpAlNM7Mp+0aAceA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mvxx3fjdx3k40ycajr5wakumf2vklxqtw68xw3u2eukqwmyf3zqff66ak
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T08:27:19Z"
    mac: ENC[AES256_GCM,data:o5GXYwd4sLaBhoDL/Wiyr8oTKmSa7yXTgu1mR1NPfrK6Sf1O64PIE3IeXfasgmYdFLC83Lwc/3Sc85Mw9WN+apJBviXjFLKEwuKHsy7AYVMWjocKy7bXfQlCIt4CZkDKPgHqlvH1+WqJHm5+ZkEr9pPaetJsYwlus6in2OvcS/Q=,iv:0EphLAdjzV0Za2Hd2DMv9lMrV5PsQczQQJw2f4rAN6M=,tag:2NCwmGHA2UV+PDKGDVjxPA==,type:str]
    version: 3.13.3
