apiVersion: v1
kind: Secret
metadata:
    name: minio-secrets
    namespace: data
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:xdCstchCiR/xkMI=,iv:+yre2kgJWVoNpCKlpPnV5HIukuw3BFa1Q50onydTe20=,tag:SpVQPtBBpwzFpU5elITWyg==,type:str]
    rootPassword: ENC[AES256_GCM,data:1Zqmvs81EYZImDILs+pCT1IM5AZ6,iv:97fQNSTilGnDxP82ql9vNJTLap7zyatx+ucLLDcROzQ=,tag:hsbQDTCpAwCrbtlBLgiftw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOUNlRDVkVWlkcUdnbXgy
            N3F5enV4RXk1MlNnN3d0WUl1RjdBRGg5STJZCldSNUFmUHdMQW1sZmg5blBPZXEy
            TWNGSG8xSGYxMk9EWDladVZWdXpLRFEKLS0tIGNVWCtwYmFIbEprV2NCdVhQNTcy
            dzVSbTZKUmFwTzM3NFdkOE8wY09xYW8KIcLsyg61yOO2LV2G9PVF4/EFf/e4/Vki
            SCe9zoK8LMjLHjcjzKdDsK6m5GTaoNIc5Ur9yni3osNw2gZ7Wp8o5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mvxx3fjdx3k40ycajr5wakumf2vklxqtw68xw3u2eukqwmyf3zqff66ak
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T05:40:01Z"
    mac: ENC[AES256_GCM,data:2CnYJADW6mDByL4BPNamnMGTNVaZz2z4bz0gchLzTwIHFTp7bijWm7u2B2VI/H21RH2tB0h1sOC0f4DUa5KXD4gU2rQTqD2//0AtHlGNpicRLaH03mc66JT5iTiabsKIoks/AFEJ1jfVJSaqqg8HIOUo2blYec7DUm3TwI0QVzk=,iv:lanltoyfhUtPbuKve8Zfp7kV0C8A+hFJvY2GAkL/aXY=,tag:pbiYfUkBAIX7/zyISbzsNg==,type:str]
    version: 3.13.3
