apiVersion: v1
kind: Secret
metadata:
    name: mysql-secrets
    namespace: data
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:Umrn0ACdWPBC7cdi9+hidDmgYg==,iv:nNnPo4GRTLTOkoUe+2PlMfsZxLm0QmSwNWKI+dFunHw=,tag:BhXeCteWnQ8IgkV2FL0HfQ==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:ovEFXt1Gxw==,iv:GloVV6hnFUlq/4h1rQL2bx9Zhbkbao53stpMZAB4YQQ=,tag:ZeHSNQAFh5qWjXr1GeyJXQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:d3RcQCd+4OZfTP/Ft8OlPg==,iv:PPVwN1CFEwZnV4+KnvH0IKG5WddBN/LgD5bJq3iAuSU=,tag:1a+5o04cLQmGmYV0HzzbNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ekNXV1pZRjY2NmIyemkr
            TENzZGl1M3k0UktJQnU3NmxObHloU2tvOTNrClZ6cjMxQ2ltMDU2eUhjZDQrRTJL
            aGVVZkZHN2pCalgrL3FtYVMyUzZ2TFUKLS0tIE9hZTROWHNMb0EvOHlHUmdxSkZw
            ekJUQ004aDVpYXpuQWx5NVVxOVhsZVEKOy4MdLag/n5HPt+m36ivKu+2bhfab0Mo
            yL6KEAoeBeCAI9jD8XMFfkK8cdW90smeLoirOyCzXUO9cuiJD7C5TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17mvxx3fjdx3k40ycajr5wakumf2vklxqtw68xw3u2eukqwmyf3zqff66ak
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T08:27:19Z"
    mac: ENC[AES256_GCM,data:9qeNEipRR7BiAmfsHZm44hYqmUfDXX1YKZ0JdNFqqjtGpIjJTYYjP/39/ZkPn9UTMOWmvXEFvM1VjYx6181Xp7wM2zJOz5VsQtZXUnR3cv18r2bejbowVeKOssq+KJ4K7BpS7Y0DZVY1pOAuKMlJJLYH9A94imHdpzPpW6iTvO4=,iv:EgeB295khUSyFXv+5z52aPG/0pw6fCZKGSFWdGtN2qA=,tag:fL+mqHT/KK9N31fLObj7mw==,type:str]
    version: 3.13.3
